In [ ]:
import datetime as dt
import  mysql.connector as sql
conn=sql.connect(host='localhost',user='root',passwd='admin',database='bank')
cur = conn.cursor()
conn.autocommit = True
c = 'n'
while c == 'n':
    print()
    print('1.CREATE BANK ACCOUNT')
    print()
    print('2.TRANSACTION')
    print()
    print('3.CUSTOMER DETAILS')
    print()
    print('4.TRANSACTION DETAILS')
    print()
    print('5.DELETE ACCOUNT')
    print()
    print('6.QUIT')

    print()
    n=int(input('Enter your CHOICE='))
    print()

    if n == 1:
        acc_no=int(input('Enter your ACCOUNT NUMBER='))
        print()
        acc_name=input('Enter your ACCOUNT NAME=')
        print()
        ph_no=int(input('Enter your PHONE NUMBER='))
        print()
        add=(input('Enter your place='))
        print()
        cr_amt=int(input('Enter your credit amount='))
        V_SQLInsert="INSERT  INTO customer_details values (" +  str (acc_no) + ",' " + acc_name + " ',"+str(ph_no) + ",' " +add + " ',"+ str (cr_amt) + " ) "
        cur.execute(V_SQLInsert)
        print()
        print('Account Created Succesfully!!!!!')
        conn.commit()
    

    if n == 2:
        acct_no=int(input('Enter Your Account Number='))
        cur.execute('select * from customer_details where acct_no='+str (acct_no) )
        data=cur.fetchall()
        count=cur.rowcount
        conn.commit()
        if count == 0:
            print()
            print('Account Number Invalid Sorry Try Again Later')
            print()
        else:
            print()
            print('1.WITHDRAW AMOUNT')
            print()
            print('2.ADD AMOUNT')
            print()
            print()
            x=int(input('Enter your CHOICE='))
            print()
            if x == 1:
                amt=int(input('Enter withdrawl amount='))
                cr_amt=0
                cur.execute('update customer_details set   cr_amt=cr_amt-'+str(amt) +  ' where acct_no=' +str(acct_no) )
                V_SQLInsert="INSERT  INTO transactions values ({} , '{}' , {} , {}) ".format(acct_no,dt.datetime.today(),amt,cr_amt) 
                cur.execute(  V_SQLInsert)
                conn.commit()
                print()
                print('Account Updated Succesfully!!!!!')
            if x == 2:
                amt=int(input('Enter amount to be added='))
                cr_amt=0
                cur.execute('update customer_details set  cr_amt=cr_amt+'+str(amt) +  ' where acct_no=' +str(acct_no) )
                V_SQLInsert="INSERT  INTO transactions values ({} , '{}' , {} , {}) ".format(acct_no,dt.datetime.today(),cr_amt,amt)
                cur.execute(  V_SQLInsert)
                conn.commit()
                print()
                print('Account Updated Succesfully!!!!!')

    if n == 3:
        acct_no=int(input('Enter your account number='))
        print()
        cur.execute('select * from customer_details where acct_no='+str(acct_no) )
        if cur.fetchone() is  None:
            print()
            print('Invalid Account number')
        else:
            cur.execute('select * from customer_details where acct_no='+str(acct_no) )
            data=cur.fetchall()
            for row in data:
                print('ACCOUNT NO=',acct_no)
                print()
                print('ACCOUNT NAME=',row[1])
                print()
                print(' PHONE NUMBER=',row[2])
                print()
                print('ADDRESS=',row[3])
                print()
                print('cr_amt=',row[4])
    if n == 4:
        acct_no=int(input('Enter your account number='))
        print()
        cur.execute('select * from customer_details where acct_no='+str(acct_no) )
        if cur.fetchone() is  None:
            print()
            print('Invalid Account number')
        else:
            cur.execute('select * from transactions where acct_no='+str(acct_no) )
            data=cur.fetchall()
            for row in data:
                print('ACCOUNT NO=',acct_no)
                print()
                print('DATE=',row[1])
                print()
                print(' WITHDRAWAL AMOUNT=',row[2])
                print()
                print('AMOUNT ADDED=',row[3])
                print()
                               

    if n == 5:
        print('DELETE YOUR ACCOUNT')
        print()
        acct_no=int(input('Enter your account number='))
        cur.execute('select * from customer_details where acct_no='+str (acct_no) )
        data=cur.fetchall()
        count=cur.rowcount
        conn.commit()
        if count == 0:
            print()
            print('Account Number Invalid Sorry Try Again Later')
            print()
        else:
            cur.execute('delete from customer_details where acct_no='+str(acct_no) )
            cur.execute('delete from transactions where acct_no='+str(acct_no) )
            print()
            print('ACCOUNT DELETED SUCCESFULLY')
                                
    if n == 6:
        print('DO YO WANT TO EXIT(y/n)')
        c=input ('enter your choice=')
    else:
        print('THANK YOU PLEASE VISIT AGAIN')
        quit()

1.CREATE BANK ACCOUNT

2.TRANSACTION

3.CUSTOMER DETAILS

4.TRANSACTION DETAILS

5.DELETE ACCOUNT

6.QUIT

Enter your CHOICE=1

Enter your ACCOUNT NUMBER=12345

Enter your ACCOUNT NAME=Dhanesh

Enter your PHONE NUMBER=56789

Enter your place=chennai

Enter your credit amount=10000

Account Created Succesfully!!!!!
THANK YOU PLEASE VISIT AGAIN

1.CREATE BANK ACCOUNT

2.TRANSACTION

3.CUSTOMER DETAILS

4.TRANSACTION DETAILS

5.DELETE ACCOUNT

6.QUIT

Enter your CHOICE=2

Enter Your Account Number=12345

1.WITHDRAW AMOUNT

2.ADD AMOUNT


Enter your CHOICE=1

Enter withdrawl amount=5000

Account Updated Succesfully!!!!!
THANK YOU PLEASE VISIT AGAIN

1.CREATE BANK ACCOUNT

2.TRANSACTION

3.CUSTOMER DETAILS

4.TRANSACTION DETAILS

5.DELETE ACCOUNT

6.QUIT

Enter your CHOICE=4

Enter your account number=12345

ACCOUNT NO= 12345

DATE= 2024-03-05

 WITHDRAWAL AMOUNT= 5000

AMOUNT ADDED= 0

THANK YOU PLEASE VISIT AGAIN

1.CREATE BANK ACCOUNT

2.TRANSACTION

3.CUSTOMER DETAILS

4.TRANSACTION DETAILS

5.DELETE ACCOUNT

6.QUIT

Enter your CHOICE=1

Enter your ACCOUNT NUMBER=09876

Enter your ACCOUNT NAME=Soundharajan

Enter your PHONE NUMBER=57899

Enter your place=Thandalam

Enter your credit amount=10000

Account Created Succesfully!!!!!
THANK YOU PLEASE VISIT AGAIN

1.CREATE BANK ACCOUNT

2.TRANSACTION

3.CUSTOMER DETAILS

4.TRANSACTION DETAILS

5.DELETE ACCOUNT

6.QUIT